### ISSUE TITLE
Apply new logo to the community's page at meetup.com

### ISSUE THREAD

**Issue by viniciusalmeida** [valleyofdevelopers/valleyofdevelopers.github.io#29]
Here is the current group's logo:
![screenshot 2017-10-20 10 07 46](https://user-images.githubusercontent.com/361296/31820133-9b41c93c-b57e-11e7-8fe9-55ce56342a24.png)

My proposal is to apply the logo created in https://github.com/valleyofdevelopers/valleyofdevelopers.github.io/issues/6.

**Comment by paulodiovani** [comment]
@viniciusalmeida  https://www.meetup.com/Vale-dos-Desenvolvedores/

**Comment by viniciusalmeida** [comment]
Sweet! I'm not sure if is it enough to change this attached image in Facebook posts (my example) or Tweets but for now we are good.
